name: test
on:
  repository_dispatch:
    types: [bbs-upload]
  workflow_dispatch:

jobs:
  upload-ftp:
    runs-on: ubuntu-latest
    steps:
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - uses: actions/checkout@v4

      - name: 安装 lftp
        run: sudo apt-get update -qq && sudo apt-get install -y lftp

      - name: 一行版终极方案
        env:
          HOST: ${{ secrets.BEGET_FTP_HOST }}
          USER: ${{ secrets.BEGET_FTP_USER }}
          PASS: ${{ secrets.BEGET_FTP_PASS }}
        run: >-
          lftp -u $USER,$PASS -p 990 ftps://$HOST
          -e "set ssl:verify-certificate false;
              set ftp:ssl-protect-data true;
              mirror -R -P=10 --delete --verbose ./bbs /bbs;
              bye"
