name: test
# 触发条件
on:
  push:
    branches:
      - main
    paths:
      - all.html
  workflow_dispatch:

permissions: write-all
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai' 
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: 执行任务 -update ftp
        uses: matteodf/lftp-upload@v1
        with:
          host: ${{ secrets.BEGET_FTP_HOST }}
          username: ${{ secrets.BEGET_FTP_USER }}
          password: ${{ secrets.BEGET_FTP_PASS }}
          localDir: ./bbs/
          remoteDir: bbs1/
          forceSsl: "false"
          
