name: update_to_FreeHostia_ftp
# 触发条件
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["bakup_ssh_dataonline"]
    types: [completed]
    branches:
      - main

jobs:
  # 第一步：判断是否需要触发
  check-trigger:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Check if size.txt was updated
        id: check
        run: |
          MSG="${{ github.event.workflow_run.head_commit.message }}"
          if [[ "$MSG" == "update size.txt" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
            echo "size.txt 已更新，准备上传 FTP"
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
            echo "size.txt 未更新，跳过 FTP 上传"
          fi

  # 第二步：只有在 size.txt 变了才运行
  upload-ftp:
    needs: check-trigger
    if: ${{ needs.check-trigger.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    permissions: write-all
    #真正的开始
    steps:
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai' 
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: 📦 Install ncftp
        run: sudo apt-get update && sudo apt-get install -y ncftp
      - name: 执行任务 -update ftp
        env:
          FREEHOSTIA_HOST: ${{ secrets.FREEHOSTIA_FTP_HOST }}
          FREEHOSTIA_USER: ${{ secrets.FREEHOSTIA_FTP_USER }}
          FREEHOSTIA_PASS: ${{ secrets.FREEHOSTIA_FTP_PASS }}
        run: |
           cd ./bbs
           ncftpput -R -u ${FREEHOSTIA_USER} -p ${FREEHOSTIA_PASS} ${FREEHOSTIA_HOST} /bbs ./*
           #-R是递归上传文件夹
           #-u user
           #-p pass
           #host (不带ftp://)
           #/ 远程目录
           #./test/ 本地目录
