name: update_to_serv00_ssh

# 触发条件
on:
  workflow_dispatch:      # 手动触发（也可以改成 push）
  workflow_run:
    workflows: ["bakup_ssh_dataonline"] # 你的 backup 工作流名字
    types: [completed]
    branches:
      - main
permissions: write-all
jobs:
  check-size-change:
    runs-on: ubuntu-latest
    # 只有 backup 成功 + 提交消息包含 "update rx.db size" 才运行
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          contains(github.event.workflow_run.head_commit.message, 'update rx.db size') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload bbs
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERV00_SSH_HOST }}
          username: ${{ secrets.SERV00_SSH_USER }}
          key: ${{ secrets.SERV00_SSH_KEY }}
          port: 22
          #上传到目录下的 bbs 目录（相对路径）
          source: "bbs/"
          target: "domains/${{ secrets.SERV00_SSH_HOST }}/public_html/"
