name: update_to_FreeHostia_ftp
# 触发条件
on:
  workflow_dispatch:
  repository_dispatch:
    types: [update-ftp]
  push:
    branches:
      - main
    paths:
      - '**/size.txt'
  #workflow_run:
    #workflows: ["serv00_ssh_bakup"]
    #types: [completed]
permissions: write-all
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai' 
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: 📦 Install ncftp
        run: sudo apt-get update && sudo apt-get install -y ncftp
      - name: 执行任务 -update ftp
        env:
          FREEHOSTIA_HOST: ${{ secrets.FREEHOSTIA_FTP_HOST }}
          FREEHOSTIA_USER: ${{ secrets.FREEHOSTIA_FTP_USER }}
          FREEHOSTIA_PASS: ${{ secrets.FREEHOSTIA_FTP_PASS }}
        run: |
           cd ./bbs
           ncftpput -R -u ${FREEHOSTIA_USER} -p ${FREEHOSTIA_PASS} ${FREEHOSTIA_HOST} /bbs ./*
           #-R是递归上传文件夹
           #-u user
           #-p pass
           #host (不带ftp://)
           #/ 远程目录
           #./test/ 本地目录
