name: update_to_FreeHostia_ftp
# 触发条件
on:
  workflow_dispatch:
  #push:
    #branches:
      #- main
    #paths:
      #- 'rxbbs.tar.gz'
  workflow_run:
    workflows: ["bakup_ssh_dataonline"] # 你的 backup 工作流名字
    types: [completed]
    branches:
      - main
permissions: write-all
jobs:
  check-size-change:
    runs-on: ubuntu-latest
    # 只有 backup 成功 + 提交消息包含 "update rx.db size" 才运行
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          contains(github.event.workflow_run.head_commit.message, 'update rx.db size') }}
    steps:
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai' 
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: 📦 Install ncftp
        run: sudo apt-get update && sudo apt-get install -y ncftp
      - name: 执行任务 -update ftp
        env:
          FREEHOSTIA_HOST: ${{ secrets.FREEHOSTIA_FTP_HOST }}
          FREEHOSTIA_USER: ${{ secrets.FREEHOSTIA_FTP_USER }}
          FREEHOSTIA_PASS: ${{ secrets.FREEHOSTIA_FTP_PASS }}
        run: |
           cd ./bbs
           ncftpput -R -u ${FREEHOSTIA_USER} -p ${FREEHOSTIA_PASS} ${FREEHOSTIA_HOST} /bbs ./*
           #-R是递归上传文件夹
           #-u user
           #-p pass
           #host (不带ftp://)
           #/ 远程目录
           #./test/ 本地目录
