name: 暂停_update_to_xrea_ftp
#因使用xrea备份暂停使用
#关掉了触发条件
# 触发条件
on:
  #repository_dispatch:
    #types: [bbs-upload]
  workflow_dispatch:  # 保留手动触发
jobs:
  upload-ftp:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai' 
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
      - name: 📦 Install ncftp
        run: sudo apt-get update && sudo apt-get install -y ncftp
      - name: 执行任务 -update ftp
        env:
          XREA_HOST: ${{ secrets.XREA_FTP_HOST }}
          XREA_USER: ${{ secrets.XREA_FTP_USER }}
          XREA_PASS: ${{ secrets.XREA_FTP_PASS }}
        run: |
           cd ./bbs
           ncftpput -R -u ${XREA_USER} -p ${XREA_PASS} ${XREA_HOST} /public_html/bbs ./*
           #-R是递归上传文件夹
           #-u user
           #-p pass
           #host (不带ftp://)
           #/ 远程目录
           #./test/ 本地目录
