name: down_FreeHostia_目录
# 触发条件
on:
  workflow_dispatch:
  #workflow_run:
    #workflows: ["update_tvobx"]
    #types: [completed]

#on:
  #push:
    #branches:
      #- main
    #paths:
      #- 'tvbox/baby.json'
  #workflow_dispatch:

permissions: write-all
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai' 
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: 📦 Install ncftp
        run: sudo apt-get update && sudo apt-get install -y ncftp
      - name: 执行任务 -update ftp
        env:
          FREEHOSTIA_HOST: ${{ secrets.FREEHOSTIA_FTP_HOST }}
          FREEHOSTIA_USER: ${{ secrets.FREEHOSTIA_FTP_USER }}
          FREEHOSTIA_PASS: ${{ secrets.FREEHOSTIA_FTP_PASS }}
        run: |
           mkdir -p ./bbs/rxdb ./bbs/files ./bbs/images ./bbs/styles
           cd ./bbs/rxdb
           ncftpget -R -T -v ftp://${FREEHOSTIA_USER}:${FREEHOSTIA_PASS}@${FREEHOSTIA_HOST}/rx/rxdb/ .
           cd ../files
           ncftpget -R -T -v ftp://${FREEHOSTIA_USER}:${FREEHOSTIA_PASS}@${FREEHOSTIA_HOST}/rx/files/ .
           cd ../images
           ncftpget -R -T -v ftp://${FREEHOSTIA_USER}:${FREEHOSTIA_PASS}@${FREEHOSTIA_HOST}/rx/images/ .
           cd ../styles
           ncftpget -R -T -v ftp://${FREEHOSTIA_USER}:${FREEHOSTIA_PASS}@${FREEHOSTIA_HOST}/rx/styles/ .
           #下载ncftpget ncftpget -R -u ${FREEHOSTIA_USER}:${FREEHOSTIA_PASS} ftp://${FREEHOSTIA_HOST}/rx/rxdb/ ./bbs/rxdb/
           #上传ncftpput -R -u ${FREEHOSTIA_USER} -p ${FREEHOSTIA_PASS} ${FREEHOSTIA_HOST} / ./test/
           #-R是递归上传文件夹
           #-u user
           #-p pass
           #host (不带ftp://)
           #/ 远程目录
           #./test/ 本地目录
      - name: Commit
        id: commit
        continue-on-error: true
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add ./
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S') update bbs done"
          git pull --rebase
      - name: 推送更改
        uses:  ad-m/github-push-action@master
        with:
          branch: main
