name: 暂停使用update_to_serv00_ssh
# 触发条件
on:
  #repository_dispatch:
    #types: [bbs-upload]
  workflow_dispatch:  # 保留手动触发
jobs:
  upload-ftp:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Upload bbs
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERV00_SSH_HOST }}
          username: ${{ secrets.SERV00_SSH_USER }}
          key: ${{ secrets.SERV00_SSH_KEY }}
          port: 22
          #上传到目录下的 bbs 目录（相对路径）
          source: "bbs/"
          target: "domains/${{ secrets.SERV00_SSH_HOST }}/public_html/"
